name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to Render backend
        run: |
          echo "Pinging https://ahnaf-farming-backend-gqds.onrender.com at $(date)"
          response=$(curl -s -o /dev/null -w "%{http_code}" https://ahnaf-farming-backend-gqds.onrender.com)
          echo "Response code: $response"
